# Generated by Django 5.2.1 on 2025-05-30 05:50

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0002_alter_user_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='photo',
        ),
        migrations.AlterField(
            model_name='user',
            name='date',
            field=models.DateField(null=True, validators=[django.core.validators.MaxValueValidator(limit_value=datetime.date(2007, 6, 4), message='You must be 18 or older to use this service')]),
        ),
    ]
